# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'PhotosFrameworkUsage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PhotosFrameworkUsage

pod 'SDWebImage'
pod 'AFNetworking'
pod 'IQKeyboardManager'
pod 'FMDB'
pod 'MBProgressHUD'

end
